const express = require('express');
const router = express.Router();
const db = require('../db');
const { requireRole } = require('./auth');

// @route   GET /api/notifications
// @desc    Get system alerts for Admin
// @access  Private (Admin only)
router.get('/', requireRole(['admin']), async (req, res) => {
    try {
        // Mocking notification data that would normally be generated by the Compliance Engine
        const mockNotifications = [
            { id: 1, type: 'Missing', message: 'XYZ Manufacturing missed Q1 submission', severity: 'error', time: '2 hours ago' },
            { id: 2, type: 'Abnormal', message: 'LMN Textiles reported 300% water usage spike', severity: 'warning', time: '5 hours ago' },
            { id: 3, type: 'New Industry', message: 'New registration request from Sunrise Foods', severity: 'info', time: '1 day ago' },
        ];
        res.json(mockNotifications);
    } catch (err) {
        res.status(500).send('Server Error');
    }
});

module.exports = router;
