const express = require('express');
const router = express.Router();
const db = require('../db');
const { requireRole } = require('./auth');
const { recordAudit } = require('./audit');
const { buildXlsx } = require('../utils/xlsx');
const { getFilingMatrix } = require('../services/missingSubmissionEngine');
const { forecast, quarterlySeries, METRIC_CONFIG } = require('../services/forecastService');

// ============================================================
// reports.js — reporting layer (Phase 20).
//
// Every report is generated from live records and carries a
// metadata block (period, timestamp, source, filters, generated
// by, caveats). "Excel" exports are REAL XLSX files (typed
// cells, built in-repo with node:zlib — no CSVs renamed).
// Insufficient data is stated in the report, never papered over.
// ============================================================

// Canonical-unit formatting note used across reports.
const UNIT_NOTE = 'Canonical units: INR / count / KL / kWh / MT. Display scaling (e.g. ₹ Crore) is applied in this table only.';

// Minimal valid PDF (kept for text reports; single page).
function minimalPdf(title, lines) {
    const esc = (s) => String(s).replace(/([()\\])/g, '\\$1');
    const body = [title, '', ...lines].map(l => `(${esc(l)}) Tj 0 -14 Td`).join('\n');
    const content = `BT /F1 9 Tf 40 800 Td\n${body}\nET`;
    const objects = [
        '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
        '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
        '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj',
        `4 0 obj << /Length ${content.length} >> stream\n${content}\nendstream endobj`,
        '5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj'
    ];
    return `%PDF-1.4\n${objects.join('\n')}\ntrailer << /Root 1 0 R /Size 6 >>\n%%EOF`;
}

// ------------------------------------------------------------
// Dataset builders per report type → { title, meta, headers, rows, caveat }
// ------------------------------------------------------------
async function buildReport(type, req) {
    const generatedBy = req.user ? `${req.user.role} #${req.user.id}` : 'system';
    const year = parseInt(req.query.year) || new Date().getUTCFullYear();
    const metaBase = [
        ['Generated (UTC)', new Date().toISOString()],
        ['Generated by', generatedBy],
        ['Data source', 'THOZHIRPORUL live PostgreSQL (filings, calendar, findings)'],
        ['Report period', `${year}` + (req.query.quarter ? ` Q${req.query.quarter}` : '')],
        ['Filters', req.query.parkId ? `park=${req.query.parkId}` : 'none']
    ];

    if (type === 'industry_data') {
        const { rows } = await db.query(`
            WITH latest AS (
                SELECT DISTINCT ON (ds.industry_id) ds.id, ds.industry_id, ds.period_year, ds.period_quarter
                  FROM data_submissions ds
              ORDER BY ds.industry_id, ds.period_year DESC, ds.period_quarter DESC NULLS LAST)
            SELECT ip.company_name, ip.location, ip.operational_status,
                   p.name AS park, l.period_year, l.period_quarter,
                   f.investment_amount, f.annual_turnover,
                   COALESCE(e.permanent_employees,0)+COALESCE(e.contract_employees,0) AS employment,
                   r.water_consumption, r.power_usage, c.amount_spent AS csr_inr,
                   (SELECT COUNT(*)::int FROM submission_versions sv WHERE sv.submission_id = l.id) AS versions
              FROM industry_profiles ip
         LEFT JOIN industrial_parks p ON p.id = ip.park_id
         LEFT JOIN latest l ON l.industry_id = ip.id
         LEFT JOIN financial_data f ON f.submission_id = l.id
         LEFT JOIN employment_data e ON e.submission_id = l.id
         LEFT JOIN resource_usage r ON r.submission_id = l.id
         LEFT JOIN csr_activities c ON c.submission_id = l.id
          ORDER BY ip.company_name`);
        return {
            title: 'Industry Data Report',
            meta: [...metaBase, ['Units', UNIT_NOTE]],
            headers: ['Company', 'Park', 'Location', 'Operational status', 'Latest period', 'Investment (Cr)', 'Turnover (Cr)', 'Employment', 'Water (KL)', 'Power (kWh)', 'CSR (INR)', 'Versions'],
            rows: rows.map(r => [r.company_name, r.park || '—', r.location || '—', r.operational_status || '—',
                r.period_year ? `${r.period_year}-Q${r.period_quarter ?? 'FY'}` : 'no filing',
                r.investment_amount === null ? null : Math.round(Number(r.investment_amount) / 1e7 * 100) / 100,
                r.annual_turnover === null ? null : Math.round(Number(r.annual_turnover) / 1e7 * 100) / 100,
                r.employment, r.water_consumption, r.power_usage, r.csr_inr, r.versions || 0])
        };
    }

    if (type === 'park_intelligence') {
        const { rows } = await db.query(`
            WITH latest AS (
                SELECT DISTINCT ON (ds.industry_id) ds.id, ds.industry_id
                  FROM data_submissions ds ORDER BY ds.industry_id, submitted_at DESC)
            SELECT p.name, COUNT(ip.id) AS industries,
                   COUNT(ip.id) FILTER (WHERE ip.operational_status = 'OPERATING') AS operating,
                   COALESCE(SUM(f.investment_amount),0) AS invest, COALESCE(SUM(f.annual_turnover),0) AS turnover,
                   COALESCE(SUM(e.permanent_employees + e.contract_employees),0) AS employment,
                   COALESCE(SUM(r.water_consumption),0) AS water, COALESCE(SUM(r.power_usage),0) AS power,
                   p.water_capacity_kl, p.power_capacity_mw
              FROM industrial_parks p
         LEFT JOIN industry_profiles ip ON ip.park_id = p.id
         LEFT JOIN latest l ON l.industry_id = ip.id
         LEFT JOIN financial_data f ON f.submission_id = l.id
         LEFT JOIN employment_data e ON e.submission_id = l.id
         LEFT JOIN resource_usage r ON r.submission_id = l.id
          GROUP BY p.name, p.water_capacity_kl, p.power_capacity_mw ORDER BY invest DESC`);
        return {
            title: 'Park Intelligence Report',
            meta: [...metaBase, ['Units', UNIT_NOTE], ['Basis', 'latest filing per industry']],
            headers: ['Park', 'Industries', 'Operating', 'Investment (Cr)', 'Turnover (Cr)', 'Employment', 'Water latest qtr (KL)', 'Power latest qtr (kWh)', 'Water capacity (KL/day)', 'Power capacity (MW)'],
            rows: rows.map(r => [r.name, r.industries, r.operating,
                Math.round(Number(r.invest) / 1e7 * 100) / 100, Math.round(Number(r.turnover) / 1e7 * 100) / 100,
                r.employment, r.water, r.power, r.water_capacity_kl, r.power_capacity_mw])
        };
    }

    if (type === 'missing_submissions') {
        const matrix = await getFilingMatrix({ year, quarter: req.query.quarter ? parseInt(req.query.quarter) : null });
        return {
            title: 'Missing Submission Report',
            meta: [...metaBase, ['Calendar', 'reporting_periods (admin-configurable deadlines)'],
                   ['Expected filers', `${matrix.summary.expected_industries} (OPERATING/IDLE/TEMPORARILY_CLOSED)`],
                   ['Caveat', 'CLOSED / UNDER_CONSTRUCTION units are not expected to file']],
            headers: ['Company', 'Park', 'Operational status', 'Outstanding periods', 'Overdue now', 'Reminders sent', 'Govt notified'],
            rows: matrix.industries.filter(i => i.outstanding.length > 0).map(i => [
                i.company_name, i.park_name, i.operational_status,
                i.outstanding.map(q => `${year}-Q${q}`).join(', ') || '—',
                i.any_overdue ? 'YES' : 'no',
                Math.max(0, ...i.periods.map(p => p.reminder_no)) || 0,
                i.periods.some(p => p.gov_notified) ? 'YES' : 'no'])
        };
    }

    if (type === 'compliance') {
        const scores = await db.query(`
            WITH latest AS (SELECT DISTINCT ON (industry_id) industry_id, overall_score
                              FROM compliance_scores ORDER BY industry_id, score_date DESC)
            SELECT ip.company_name, ls.overall_score, ip.compliance_score AS profile_sync,
                   (SELECT COUNT(*)::int FROM compliance_violations v WHERE v.industry_id = ip.id AND v.status <> 'resolved') AS open_violations,
                   (SELECT COUNT(*)::int FROM data_findings f WHERE f.industry_id = ip.id AND f.status = 'open') AS open_findings
              FROM industry_profiles ip LEFT JOIN latest ls ON ls.industry_id = ip.id ORDER BY ip.company_name`);
        return {
            title: 'Compliance Report',
            meta: [...metaBase, ['Scoring', 'computed daily from violations, findings and filing timeliness']],
            headers: ['Company', 'Latest score', 'Synced profile score', 'Open violations', 'Open data findings'],
            rows: scores.rows.map(r => [r.company_name, r.overall_score, r.profile_sync, r.open_violations, r.open_findings])
        };
    }

    if (type === 'resource_demand') {
        const [water, power] = await Promise.all([
            quarterlySeries('water', 'state', null), quarterlySeries('power', 'state', null)
        ]);
        const rows = [];
        const len = Math.max(water.length, power.length);
        for (let i = 0; i < len; i++) {
            const w = water[Math.max(0, water.length - len + i)] || {};
            const p = power[Math.max(0, power.length - len + i)] || {};
            const wp = water.length > 1 && i >= water.length - len + 1 && water[i - 1] && water[i - 1].value > 0
                ? Math.round(((water[i].value - water[i - 1].value) / water[i - 1].value) * 1000) / 10 : null;
            rows.push([`${w.year || p.year}-${w.quarter || p.quarter}`,
                w.value ?? null, wp, p.value ?? null, null]);
        }
        return {
            title: 'Resource Demand Report',
            meta: [...metaBase, ['Source', 'industry filings aggregated per quarter (statewide)'], ['Units', 'KL and kWh per quarter']],
            headers: ['Quarter', 'Water demand (KL)', 'Water QoQ %', 'Power demand (kWh)', 'Power QoQ %'],
            rows,
            caveat: water.length < 2 || power.length < 2 ? 'Fewer than two quarters of history — growth columns are intentionally blank.' : null
        };
    }

    if (type === 'anomaly') {
        const { rows } = await db.query(`
            SELECT f.finding_type, f.rule_id, ip.company_name, f.period_year, f.period_quarter,
                   f.metric, f.observed_value, f.expected_value, f.change_pct, f.severity, f.reason, f.status, f.detected_at
              FROM data_findings f JOIN industry_profiles ip ON ip.id = f.industry_id
          ORDER BY CASE f.severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'warning' THEN 2 ELSE 3 END, f.detected_at DESC
             LIMIT 500`);
        return {
            title: 'Anomaly & Consistency Findings Report',
            meta: [...metaBase, ['Detectors', 'period-over-change %, IQR fence, quota/consistency rules'],
                   ['Caveat', 'metrics with insufficient history are skipped (never scored) — see data_findings.evidence']],
            headers: ['Detected', 'Type', 'Rule', 'Company', 'Period', 'Metric', 'Observed', 'Expected', 'Change %', 'Severity', 'Status', 'Reason'],
            rows: rows.map(r => [new Date(r.detected_at).toISOString(), r.finding_type, r.rule_id, r.company_name,
                `${r.period_year}-Q${r.period_quarter ?? 'FY'}`, r.metric, r.observed_value, r.expected_value,
                r.change_pct, r.severity, r.status, r.reason])
        };
    }

    if (type === 'growth') {
        const metric = METRIC_CONFIG[req.query.metric] ? req.query.metric : 'employment';
        const series = await quarterlySeries(metric, 'state', null);
        return {
            title: `Growth Report — ${metric} (statewide)`,
            meta: [...metaBase, ['Unit', METRIC_CONFIG[metric].unit], ['Method', 'QoQ = vs previous filed quarter; YoY = vs same quarter prior year']],
            headers: ['Quarter', 'Value', 'QoQ %', 'YoY %'],
            rows: series.map((p, i) => {
                const prev = series[i - 1];
                const prevY = series.find(x => x.year === p.year - 1 && x.quarter === p.quarter);
                return [`${p.year}-Q${p.quarter}`, p.value,
                    prev && prev.value > 0 ? Math.round(((p.value - prev.value) / prev.value) * 1000) / 10 : null,
                    prevY && prevY.value > 0 ? Math.round(((p.value - prevY.value) / prevY.value) * 1000) / 10 : null];
            }),
            caveat: series.length < 2 ? 'Insufficient history for growth columns.' : null
        };
    }

    if (type === 'forecast') {
        const metric = METRIC_CONFIG[req.query.metric] ? req.query.metric : 'power';
        const fc = await forecast(metric, 'state', null, 4, { persist: false, generatedBy: `report:${req.user.id}` });
        return {
            title: `Forecast Report — ${metric} (statewide, next 4 quarters)`,
            meta: [...metaBase, ['Model', fc.model || 'none'], ['Training quarters', fc.training_periods], ['Unit', fc.unit]],
            headers: ['Period', 'Predicted', 'Lower bound', 'Upper bound'],
            rows: fc.projection.map((p, i) => [p.period, p.value, fc.band[i].low, fc.band[i].high]),
            caveat: fc.data_status !== 'OK'
                ? `INSUFFICIENT_DATA: ${fc.available_points} quarter(s) available; ${fc.minimum_required}. No projection produced.`
                : (fc.caveat || null)
        };
    }

    if (type === 'capacity') {
        const parks = (await db.query('SELECT * FROM industrial_parks ORDER BY id')).rows;
        const rows = [];
        for (const p of parks) {
            for (const metric of ['water', 'power']) {
                const series = await quarterlySeries(metric, 'park', p.id);
                const current = series.length ? series[series.length - 1].value : null;
                const fc = await forecast(metric, 'park', p.id, 4, { persist: false });
                const projected = fc.data_status === 'OK'
                    ? Math.round(fc.projection.reduce((s, x) => s + x.value, 0) / fc.projection.length)
                    : current;
                const capacity = metric === 'water'
                    ? (Number(p.water_capacity_kl) > 0 ? Math.round(Number(p.water_capacity_kl) * 91) : null)
                    : (Number(p.power_capacity_mw) > 0 ? Math.round(Number(p.power_capacity_mw) * 1000 * 2190) : null);
                const gap = capacity !== null && projected !== null ? projected - capacity : null;
                const risk = capacity === null ? 'NOT_CONFIGURED' : projected === null ? 'NO_DEMAND_DATA'
                    : (projected / capacity > 1 ? 'HIGH' : projected / capacity > 0.85 ? 'MEDIUM' : 'LOW');
                rows.push([p.name, metric, current, projected,
                    capacity, gap, risk,
                    fc.data_status === 'OK' ? fc.model : `insufficient data (${fc.available_points} qtrs)`]);
            }
        }
        return {
            title: 'Infrastructure Capacity / Demand Report',
            meta: [...metaBase,
                   ['Capacity basis', 'water: configured KL/day × 91; power: configured MW × 1000 × 2190h'],
                   ['Caveat', 'NOT_CONFIGURED = no capacity value set for the park — configure industrial_parks before planning.']],
            headers: ['Park', 'Resource', 'Current demand (qtr)', 'Projected (4-qtr mean)', 'Capacity (qtr)', 'Gap', 'Risk', 'Forecast model'],
            rows
        };
    }

    throw new Error('UNKNOWN_REPORT_TYPE');
}

// ------------------------------------------------------------
// GET /api/reports/export?type=...&format=json|csv|xlsx|pdf
// ------------------------------------------------------------
const REPORT_TYPES = ['industry_data', 'park_intelligence', 'missing_submissions', 'compliance',
                      'resource_demand', 'anomaly', 'growth', 'forecast', 'capacity'];

router.get('/export', requireRole(['admin', 'govt']), async (req, res) => {
    try {
        const type = req.query.type || 'industry_data';
        if (!REPORT_TYPES.includes(type)) {
            return res.status(400).json({ error: `Unknown report type. Valid: ${REPORT_TYPES.join(', ')}` });
        }
        const report = await buildReport(type, req);

        await recordAudit(req.user.id, 'REPORT_GENERATED', req.ip, {
            entityType: 'report', entityId: type,
            payload: { format: req.query.format || 'json', rows: report.rows.length }
        });

        if (req.query.format === 'json' || !req.query.format) {
            return res.json({ ...report, count: report.rows.length, caveats: report.caveat ? [report.caveat] : [] });
        }

        if (req.query.format === 'csv') {
            const esc = (v) => v === null || v === undefined ? '' : `"${String(v).replace(/"/g, '""')}"`;
            const lines = [
                ...report.meta.map(([k, v]) => `${esc(k)},${esc(v)}`),
                '',
                report.headers.map(esc).join(','),
                ...report.rows.map(r => r.map(esc).join(','))
            ];
            if (report.caveat) lines.push('', esc('Caveat'), esc(report.caveat));
            res.setHeader('Content-Type', 'text/csv; charset=utf-8');
            res.setHeader('Content-Disposition', `attachment; filename=THOZHIRPORUL_${type}_${Date.now()}.csv`);
            return res.send(Buffer.from('\uFEFF' + lines.join('\n'), 'utf8'));
        }

        if (req.query.format === 'xlsx') {
            // REAL XLSX — typed cells, metadata block, caveat rows.
            const buf = buildXlsx({
                sheetName: type.slice(0, 28),
                title: `THOZHIRPORUL — ${report.title}`,
                meta: [...report.meta, ...(report.caveat ? [['Caveat', report.caveat]] : [])],
                headers: report.headers,
                rows: report.rows
            });
            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            res.setHeader('Content-Disposition', `attachment; filename=THOZHIRPORUL_${type}_${Date.now()}.xlsx`);
            return res.send(buf);
        }

        if (req.query.format === 'pdf') {
            const lines = [];
            report.rows.slice(0, 60).forEach(r => lines.push(r.map(v => v === null || v === undefined ? '—' : String(v)).join(' | ')));
            if (report.rows.length > 60) lines.push(`… and ${report.rows.length - 60} more rows (export CSV/XLSX for the full set)`);
            if (report.caveat) lines.push('', `Caveat: ${report.caveat}`);
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', `attachment; filename=THOZHIRPORUL_${type}_${Date.now()}.pdf`);
            return res.send(Buffer.from(minimalPdf(`THOZHIRPORUL — ${report.title}`, lines), 'utf-8'));
        }

        return res.status(400).json({ error: 'format must be json | csv | xlsx | pdf' });
    } catch (err) {
        console.error('Report Export Error:', err.message);
        res.status(500).send('Server Error');
    }
});

// ------------------------------------------------------------
// Legacy-compatible dataset for the client-side generator
// (unchanged behaviour, canonical units retained).
// ------------------------------------------------------------
async function fetchReportRows() {
    const { rows } = await db.query(`
        WITH latest_sub AS (
            SELECT DISTINCT ON (industry_id) id, industry_id
            FROM data_submissions
            WHERE lower(status) IN ('approved', 'submitted')
            ORDER BY industry_id, submitted_at DESC
        ),
        latest_scores AS (
            SELECT DISTINCT ON (industry_id) industry_id, overall_score
            FROM compliance_scores
            ORDER BY industry_id, score_date DESC
        )
        SELECT
            ip.company_name,
            ip.location,
            ROUND(COALESCE(f.investment_amount, 0) / 1e7, 2) AS investment_cr,
            COALESCE(e.permanent_employees + e.contract_employees, 0) AS employment,
            COALESCE(r.water_consumption, 0) AS water_consumption,
            COALESCE(r.power_usage, 0) AS power_usage,
            ls2.overall_score AS compliance
        FROM industry_profiles ip
        LEFT JOIN latest_sub ls ON ls.industry_id = ip.id
        LEFT JOIN financial_data f ON f.submission_id = ls.id
        LEFT JOIN employment_data e ON e.submission_id = ls.id
        LEFT JOIN resource_usage r ON r.submission_id = ls.id
        LEFT JOIN latest_scores ls2 ON ls2.industry_id = ip.id
        ORDER BY investment_cr DESC NULLS LAST, ip.company_name ASC
    `);
    return rows;
}

// @route   GET /api/reports/data
router.get('/data', requireRole(['admin', 'govt']), async (req, res) => {
    try {
        const rows = await fetchReportRows();
        const totals = rows.reduce((acc, r) => {
            acc.investment += parseFloat(r.investment_cr) || 0;
            acc.employment += parseInt(r.employment) || 0;
            acc.water += parseFloat(r.water_consumption) || 0;
            acc.power += parseFloat(r.power_usage) || 0;
            return acc;
        }, { investment: 0, employment: 0, water: 0, power: 0 });
        res.json({ rows, totals, count: rows.length, generatedAt: new Date().toISOString() });
    } catch (err) {
        console.error('Report Data Error:', err.message);
        res.status(500).send('Server Error');
    }
});

// ------------------------------------------------------------
// POST /api/reports/generate — legacy endpoint, now HONEST:
// PDF stays a minimal PDF, CSV stays CSV, and format "Excel"
// produces a REAL XLSX (previously CSV bytes renamed — fixed).
// ------------------------------------------------------------
router.post('/generate', requireRole(['admin', 'govt']), async (req, res) => {
    const { reportType, timePeriod, period, format } = req.body;
    const reportPeriod = timePeriod || period || 'current';
    try {
        const rows = await fetchReportRows();
        const totals = rows.reduce((acc, r) => {
            acc.investment += parseFloat(r.investment_cr) || 0;
            acc.employment += parseInt(r.employment) || 0;
            acc.water += parseFloat(r.water_consumption) || 0;
            acc.power += parseFloat(r.power_usage) || 0;
            return acc;
        }, { investment: 0, employment: 0, water: 0, power: 0 });

        const reportTitle = ({
            investment: 'Investment Summary', employment: 'Employment Report',
            compliance: 'Compliance Status', park_performance: 'Park Performance',
            resource: 'Resource Utilization'
        })[reportType] || 'Industrial Report';
        const generatedAt = new Date().toISOString();
        const headers = ['Company', 'Location', 'Investment (Cr)', 'Employment', 'Water (KL)', 'Power (kWh)', 'Compliance (%)'];

        if (format === 'PDF') {
            const lines = [
                `THOZHIRPORUL — ${reportTitle}   Period: ${reportPeriod}`,
                `Generated: ${generatedAt}   Source: live filings`,
                '',
                headers.join(' | '),
                ...rows.map(r => `${r.company_name} | ${r.location || '-'} | ${r.investment_cr} | ${r.employment} | ${r.water_consumption} | ${r.power_usage} | ${r.compliance != null ? r.compliance + '%' : 'N/A'}`),
                '',
                `TOTAL: Investment ${totals.investment.toFixed(2)} Cr | Employment ${totals.employment} | Industries ${rows.length}`
            ];
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', `attachment; filename=Report_${reportType}_${reportPeriod}.pdf`);
            return res.send(Buffer.from(minimalPdf(`THOZHIRPORUL — ${reportTitle}`, lines), 'utf-8'));
        }

        if (format === 'Excel' || format === 'xlsx') {
            // REAL XLSX — validated by the E2E suite (TEST 9).
            const buf = buildXlsx({
                sheetName: 'Report',
                title: `THOZHIRPORUL — ${reportTitle}`,
                meta: [['Period', reportPeriod], ['Generated (UTC)', generatedAt], ['Source', 'live filings (latest per industry)'], ['Units', UNIT_NOTE]],
                headers,
                rows: rows.map(r => [r.company_name, r.location || '', r.investment_cr, r.employment, r.water_consumption, r.power_usage, r.compliance])
            });
            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            res.setHeader('Content-Disposition', `attachment; filename=Report_${reportType}_${reportPeriod}.xlsx`);
            return res.send(buf);
        }

        if (format === 'CSV') {
            const esc = (v) => v === null || v === undefined ? '' : `"${String(v).replace(/"/g, '""')}"`;
            const csv = [headers.map(esc).join(','),
                ...rows.map(r => [r.company_name, r.location || '', r.investment_cr, r.employment, r.water_consumption, r.power_usage, r.compliance].map(esc).join(',')),
                ['TOTAL', '', totals.investment.toFixed(2), totals.employment, totals.water, totals.power, ''].map(esc).join(',')].join('\n');
            res.setHeader('Content-Type', 'text/csv; charset=utf-8');
            res.setHeader('Content-Disposition', `attachment; filename=Report_${reportType}_${reportPeriod}.csv`);
            return res.send(Buffer.from('\uFEFF' + csv, 'utf8'));
        }

        res.status(400).json({ msg: 'Unsupported format requested (use PDF, XLSX/Excel or CSV)' });
    } catch (err) {
        console.error("Report Generation Error:", err.message);
        res.status(500).send('Server Error during Report Generation.');
    }
});

// ------------------------------------------------------------
// chart-data / comparison / log / executive-summary (preserved).
// ------------------------------------------------------------
function parsePeriod(p) {
    if (!p) return {};
    const m = String(p).match(/^(\d{4})(?:[-/](Q([1-4])|S([12]))?)?$/i);
    if (!m) return {};
    const quarter = m[3] ? parseInt(m[3]) : (m[4] ? parseInt(m[4]) : null);
    return { year: parseInt(m[1]), quarter };
}

router.get('/chart-data', requireRole(['admin', 'govt']), async (req, res) => {
    try {
        const metric = ['investment', 'employment', 'compliance'].includes(req.query.metric)
            ? req.query.metric : 'investment';

        let sql;
        if (metric === 'investment') {
            sql = `SELECT ds.period_year AS period, ROUND(COALESCE(SUM(f.investment_amount),0)/1e7, 2) AS value
                     FROM data_submissions ds JOIN financial_data f ON f.submission_id = ds.id
                    WHERE ds.period_year IS NOT NULL GROUP BY ds.period_year ORDER BY ds.period_year`;
        } else if (metric === 'employment') {
            sql = `SELECT ds.period_year AS period, COALESCE(SUM(COALESCE(e.permanent_employees,0) + COALESCE(e.contract_employees,0)),0) AS value
                     FROM data_submissions ds JOIN employment_data e ON e.submission_id = ds.id
                    WHERE ds.period_year IS NOT NULL GROUP BY ds.period_year ORDER BY ds.period_year`;
        } else {
            sql = `SELECT to_char(score_date,'YYYY-MM') AS period, ROUND(AVG(overall_score),1) AS value
                     FROM compliance_scores GROUP BY 1 ORDER BY 1`;
        }
        const { rows } = await db.query(sql);
        res.json({ metric, points: rows });
    } catch (err) {
        console.error('Chart Data Error:', err.message);
        res.status(500).send('Server Error');
    }
});

router.get('/comparison', requireRole(['admin', 'govt']), async (req, res) => {
    try {
        const metric = ['investment', 'employment', 'compliance'].includes(req.query.metric)
            ? req.query.metric : 'investment';
        const a = req.query.periodA, b = req.query.periodB;
        if (!a || !b) return res.status(400).json({ error: 'periodA and periodB required (e.g. 2024, 2025-Q1)' });

        async function totalFor(period) {
            const { year, quarter } = parsePeriod(period);
            if (!year) return 0;
            if (metric === 'investment') {
                const sql = quarter
                    ? `SELECT COALESCE(SUM(f.investment_amount),0) AS v FROM data_submissions ds JOIN financial_data f ON f.submission_id=ds.id WHERE ds.period_year=$1 AND ds.period_quarter=$2`
                    : `SELECT COALESCE(SUM(f.investment_amount),0) AS v FROM data_submissions ds JOIN financial_data f ON f.submission_id=ds.id WHERE ds.period_year=$1`;
                const r = await db.query(sql, quarter ? [year, quarter] : [year]);
                return parseFloat(r.rows[0].v) || 0;
            }
            if (metric === 'employment') {
                const sql = quarter
                    ? `SELECT COALESCE(SUM(COALESCE(e.permanent_employees,0)+COALESCE(e.contract_employees,0)),0) AS v FROM data_submissions ds JOIN employment_data e ON e.submission_id=ds.id WHERE ds.period_year=$1 AND ds.period_quarter=$2`
                    : `SELECT COALESCE(SUM(COALESCE(e.permanent_employees,0)+COALESCE(e.contract_employees,0)),0) AS v FROM data_submissions ds JOIN employment_data e ON e.submission_id=ds.id WHERE ds.period_year=$1`;
                const r = await db.query(sql, quarter ? [year, quarter] : [year]);
                return parseInt(r.rows[0].v) || 0;
            }
            const r = await db.query(
                `SELECT COALESCE(AVG(overall_score),0) AS v FROM compliance_scores WHERE EXTRACT(YEAR FROM score_date)=$1`, [year]);
            return parseFloat(r.rows[0].v) || 0;
        }

        const valA = await totalFor(a);
        const valB = await totalFor(b);
        const deltaPct = valA === 0 ? null : Math.round(((valB - valA) / valA) * 1000) / 10;
        res.json({ metric, periodA: a, periodB: b, valueA: valA, valueB: valB, delta_pct: deltaPct });
    } catch (err) {
        console.error('Comparison Error:', err.message);
        res.status(500).send('Server Error');
    }
});

router.post('/log', requireRole(['admin', 'govt', 'industry']), async (req, res) => {
    try {
        const { reportType, format, reportIdCode, rowCount, fileSizeKb, filters } = req.body;
        const ins = await db.query(
            `INSERT INTO report_generation_log
                (generated_by, report_type, format, report_id_code, row_count, file_size_kb, filters)
             VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb) RETURNING id`,
            [req.user.id, reportType || null, format || null, reportIdCode || null,
             rowCount || null, fileSizeKb || null, JSON.stringify(filters || {})]
        );
        res.status(201).json(ins.rows[0]);
    } catch (err) {
        console.error('Report Log Error:', err.message);
        res.status(500).send('Server Error');
    }
});

router.get('/executive-summary', requireRole(['admin', 'govt']), async (req, res) => {
    try {
        const matrix = await getFilingMatrix({ year: new Date().getUTCFullYear() });
        const totals = await db.query(`
            SELECT
              (SELECT COUNT(*) FROM industry_profiles) AS industries,
              (SELECT COUNT(*) FROM industrial_parks WHERE status='active') AS active_parks,
              (SELECT ROUND(COALESCE(SUM(total_investment_cr),0),2) FROM industrial_parks) AS investment_cr,
              (SELECT COALESCE(SUM(total_employment),0) FROM industrial_parks) AS employment`);
        const compliance = await db.query(`
            WITH latest AS (
              SELECT DISTINCT ON (industry_id) industry_id, overall_score
                FROM compliance_scores ORDER BY industry_id, score_date DESC)
            SELECT
              COUNT(*) FILTER (WHERE overall_score >= 80) AS compliant,
              COUNT(*) FILTER (WHERE overall_score >= 60 AND overall_score < 80) AS warning,
              COUNT(*) FILTER (WHERE overall_score < 60) AS non_compliant
              FROM latest`);
        const topParks = await db.query(`
            SELECT name, district, infrastructure_score, total_industries, total_investment_cr
              FROM industrial_parks ORDER BY infrastructure_score DESC NULLS LAST LIMIT 5`);
        const openViolations = await db.query(
            `SELECT COUNT(*) AS n FROM compliance_violations WHERE status <> 'resolved'`);
        const openFindings = await db.query(
            `SELECT COUNT(*) AS n FROM data_findings WHERE status = 'open' AND severity IN ('high','critical')`);

        res.json({
            as_of: new Date().toISOString(),
            headline: {
                industries: parseInt(totals.rows[0].industries),
                active_parks: parseInt(totals.rows[0].active_parks),
                investment_cr: parseFloat(totals.rows[0].investment_cr),
                employment: parseInt(totals.rows[0].employment),
                open_violations: parseInt(openViolations.rows[0].n),
                open_critical_findings: parseInt(openFindings.rows[0].n)
            },
            filing_compliance: matrix.summary,
            compliance: {
                compliant: parseInt(compliance.rows[0].compliant),
                warning: parseInt(compliance.rows[0].warning),
                non_compliant: parseInt(compliance.rows[0].non_compliant)
            },
            top_parks: topParks.rows
        });
    } catch (err) {
        console.error('Executive Summary Error:', err.message);
        res.status(500).send('Server Error');
    }
});

module.exports = router;
